{
 "title": "Détails du Trajet",
 "tags": [ "Custom" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "drive_id", "query": "2691" },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars;"
   },
   {
    "name": "alternative_length_unit",
    "query": "select case when unit_of_length = 'km' then 'm' when unit_of_length = 'mi' then 'ft' end  from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select preferred_range from settings limit 1;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Distance Parcourue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select convert_km(distance::numeric, '$length_unit') from drives where id = $drive_id;"
    }
   ]
  },
  {
   "title": "km Affichés Utilisés",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "lengthkm",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t((start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km))\nFROM\n\tdrives d\nJOIN cars car ON car.id = car_id\nWHERE\n\td.id = $drive_id;"
    }
   ]
  },
  {
   "title": "Efficience",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t(distance/(start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km))\nFROM\n\tdrives d\nJOIN cars car ON car.id = car_id\nWHERE\n\td.id = $drive_id;"
    }
   ]
  },
  {
   "title": "Consommation Affichée",
   "type": "singlestat",
   "description": "Ce qui est affiché dans la voiture.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t1000*((start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km) * 0.94 * car.efficiency)/convert_km(distance::numeric, '$length_unit')\nFROM\n\tdrives d\nJOIN cars car ON car.id = car_id\nWHERE\n\td.id = $drive_id;"
    }
   ]
  },
  {
   "title": "Consommation Théorique",
   "type": "singlestat",
   "description": "Calculée avec un la constante autonomie EPA",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t1000*((start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km) * car.efficiency)/convert_km(distance::numeric, '$length_unit')\nFROM\n\tdrives d\nJOIN cars car ON car.id = car_id\nWHERE\n\td.id = $drive_id;"
    }
   ]
  },
  {
   "title": "Durée",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT extract(epoch FROM (end_position.date - start_position.date))\nFROM drives\nLEFT JOIN positions start_position ON start_position_id = start_position.id\nLEFT JOIN positions end_position ON end_position_id = end_position.id\nWHERE drives.id = $drive_id;"
    }
   ]
  },
  {
   "title": "Vitesse Moyenne",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "format": "velocitykmh",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT distance/duration_min*60 AS avg_speed\nFROM drives\nLEFT JOIN positions start_position ON start_position_id = start_position.id\nLEFT JOIN positions end_position ON end_position_id = end_position.id\nWHERE drives.id = $drive_id;\n\n\n"
    }
   ]
  },
  {
   "title": "Énergie Utilisée Affichée",
   "type": "singlestat",
   "description": "Calculée avec ce que la voiture affiche",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t(start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km)* 0.94 * car.efficiency\nFROM\n\tdrives d\nJOIN cars car ON car.id = car_id\nWHERE\n\td.id = $drive_id;"
    }
   ]
  },
  {
   "title": "Énergie Théorique Utilisée",
   "type": "singlestat",
   "description": "Calculée avec un la constante de consommation EPA de la voiture",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t((start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km)* car.efficiency)\nFROM\n\tdrives d\nJOIN cars car ON car.id = car_id\nWHERE\n\td.id = $drive_id;"
    }
   ]
  },
  {
   "title": "Trajet",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "Niveau de Batterie (%)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t$__time(date),\n\n\tconvert_km([[preferred_range]]_battery_range_km, '$length_unit') AS \"Autonomie (théorique) [$length_unit]\",\n\tbattery_level AS \"Niveau de Batterie [%]\"\nFROM\n\tpositions\nWHERE\n car_id = $car_id AND\n $__timeFilter(date)\nORDER BY\n\tdate ASC"
    }
   ]
  },
  {
   "title": "Carte",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(date),\r\n   latitude,\r\n   longitude\r\n   FROM positions\r\nWHERE \r\n  car_id = $car_id AND \r\n  $__timeFilter(date)\r\nORDER BY date ASC"
    }
   ]
  },
  {
   "title": "Trajet",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t$__time(date),\n\tconvert_km(speed, '$length_unit') AS \"Vitesse [$length_unit/h]\",\n\tpower AS \"Puissance [kW]\",\n\tconvert_km([[preferred_range]]_battery_range_km, '$length_unit') AS \"Autonomie (théorique) [$length_unit]\",\n\tconvert_km(est_battery_range_km, '$length_unit') AS \"Autonomie (est.) [$length_unit]\",\n\tbattery_level AS \"Niveau de Batterie [%]\",\n\tusable_battery_level AS \"Niveau de Batterie Utilisable [%]\"\nFROM\n\tpositions\nWHERE\n car_id = $car_id AND\n $__timeFilter(date)\nORDER BY\n\tdate ASC"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "mètres" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t$__time(date),\n\tROUND(convert_m(elevation, '$alternative_length_unit')) AS \"Altitude [$alternative_length_unit]\"\nFROM\n\tpositions\nWHERE\n car_id = $car_id AND\n $__timeFilter(date)\nORDER BY\n\tdate ASC"
    }
   ]
  },
  {
   "title": "Température",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t$__time(date),\n\tconvert_celsius(outside_temp, '$temp_unit') AS \"Température Extérieure [°$temp_unit]\",\n\tconvert_celsius(inside_temp, '$temp_unit') AS \"Température Intérieure [°$temp_unit]\",\n\tconvert_celsius(driver_temp_setting, '$temp_unit') as \"Température Conducteur [°$temp_unit]\",\n\tconvert_celsius(passenger_temp_setting, '$temp_unit') as \"Température Passager [°$temp_unit]\",\n  is_climate_on::integer AS \"Climatisation\",\n\tfan_status AS \"Ventilation\"\nFROM\n\tpositions\nWHERE\n car_id = $car_id AND\n $__timeFilter(date)\nORDER BY\n\tdate ASC"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT CONCAT_WS(' - ', round(convert_km(start_km::numeric, '$length_unit')), round(convert_km(end_km::numeric, '$length_unit')))\nFROM drives d\nWHERE d.id = $drive_id"
    }
   ]
  }
 ]
}