{
 "title": "Détails de la Charge",
 "tags": [ "Custom" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "charging_process_id", "query": "20" },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   },
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select preferred_range from settings limit 1;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Lieu",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(g.name, CONCAT_WS(', ', COALESCE(addresses.name, CONCAT_WS(' ', addresses.road, addresses.house_number)), addresses.city))\nFROM\n\tcharging_processes c\n\tLEFT JOIN addresses ON addresses.id = c.address_id\n\tLEFT JOIN geofences g ON g.id = geofence_id\nWHERE\n\tc.id = $charging_process_id"
    }
   ]
  },
  {
   "title": "Durée",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT duration_min from charging_processes where id = $charging_process_id;"
    }
   ]
  },
  {
   "title": "Énergie Ajoutée",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT charge_energy_added from charging_processes where id = $charging_process_id;"
    }
   ]
  },
  {
   "title": "% Ajouté",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "range",
   "targets": [
    {
     "rawSql": "SELECT battery_level FROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date) and\n  p.car_id = $car_id\n\n"
    }
   ]
  },
  {
   "title": "Rechargé",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "lengthkm",
   "valueName": "range",
   "targets": [
    {
     "rawSql": "SELECT convert_km([[preferred_range]]_battery_range_km, '$length_unit') FROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date) and\n  p.car_id = $car_id\n\n"
    }
   ]
  },
  {
   "title": "Début",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "lengthkm",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT convert_km([[preferred_range]]_battery_range_km, '$length_unit') FROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date) and\n  p.car_id = $car_id\n\n"
    }
   ]
  },
  {
   "title": "Fin",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "lengthkm",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT convert_km([[preferred_range]]_battery_range_km, '$length_unit') FROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date) and\n  p.car_id = $car_id\n\n"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "kwatt", "label": "Puissance (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(date),\r\n  battery_level as \"Niveau de Batterie [%]\",\r\n  charger_power as \"Puissance [kW]\"\r\nFROM\r\n  charges c\r\njoin\r\n  charging_processes p ON p.id = c.charging_process_id \r\nWHERE\r\n  $__timeFilter(date) and\r\n  p.car_id = $car_id\r\nORDER BY\r\n  date ASC"
    }
   ]
  },
  {
   "title": "Détails de la Charge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "Puissance (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  battery_level as \"Niveau de Batterie [%]\",\n  convert_km([[preferred_range]]_battery_range_km, '$length_unit') as \"Autonomie Théorique [$length_unit]\",\n  charger_power as \"Puissance [kW]\",\n  charger_voltage as \"Tension de Charge [V]\",\n  charger_actual_current as \"Intensité [A]\",\n  charger_pilot_current as \"Intensité (pilotée) [A]\",\n  charger_phases as \"Phases\",\n  convert_celsius(outside_temp, '$temp_unit') as \"Température Extérieure[°$temp_unit]\"\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date) and\n  p.car_id = $car_id\nORDER BY\n  date ASC"
    }
   ]
  },
  {
   "title": "Carte",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n\t$__time(date),\n\tunnest(ARRAY[latitude, latitude]) AS latitude,\n\tunnest(ARRAY[longitude, longitude]) AS longitude\nFROM\n\tcharging_processes c\n\tJOIN positions p ON c.position_id = p.id\nWHERE\n\t$__timeFilter(date)\n\tAND c.car_id = $car_id;"
    }
   ]
  },
  {
   "title": "Coût",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 21 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT cost from charging_processes where id = $charging_process_id;"
    }
   ]
  }
 ]
}