{
 "title": "Lieux",
 "tags": [ "Custom" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Nombre de Lieux Visités",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from addresses;"
    }
   ]
  },
  {
   "title": "Villes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT city)\nFROM\n\taddresses;"
    }
   ]
  },
  {
   "title": "Régions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT state)\nFROM\n\taddresses;"
    }
   ]
  },
  {
   "title": "Pays",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(DISTINCT country)\nFROM\n\taddresses;"
    }
   ]
  },
  {
   "title": "Villes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcity,\n\tcount(*) as \"# addresses\"\nFROM\n\taddresses\nWHERE\n\tcity IS NOT NULL\nGROUP BY\n\t1\nORDER BY\n\t2 DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Régions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tstate,\n\tcount(*) as \"# addresses\"\nFROM\n\taddresses\nWHERE\n\tstate IS NOT NULL\nGROUP BY\n\t1\nORDER BY\n\t2 DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Adresses Visitées",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT('new?lat=', latitude, '&lng=', longitude) as path,\n\tCOALESCE(name, CONCAT(road, ' ', house_number)) AS name,\n\tneighbourhood,\n\tcity,\n\tstate,\n\tcountry,\n\tupdated_at\nFROM\n\taddresses\nWHERE\n\t$__timeFilter(inserted_at)\nORDER BY inserted_at DESC;"
    }
   ]
  },
  {
   "title": "Lieux Enregistrés",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  id,\n\tname\nFROM\n\tgeofences\nORDER BY\n\tinserted_at DESC;"
    }
   ]
  }
 ]
}